NEW: Sent E-Mail from SpendenbescheinigungListeView
openjverein/jverein pull request #135
Opened 2024-01-29 08:24 UTC by dippeal

Mit der Erweiterung kann man das E-Mail Formular aus der Spendenbescheinigung Liste View öffnen.
Die Spendenbescheinigung wird der E-Mail **nicht** als Anhang angefügt. Ich bin noch am überlegen ob das möglich/sinnvoll ist.

Rechtlich geht das wohl nur für Geldzuwendungen und es müssen die Voraussetzungen für maschinell erstellte Spendenbescheinigungen erfüllt sein (entsprechend R 10b.1 Abs. 4 EStR).

Folgende Restriktionen sind umgesetzt:
1. Es ist eine Spendenbescheinigung ausgewählt
2. Der Buchung der Spendenbescheinigung ist ein Mitglied/Adressat zugewiesen
3. Das Mitglied/Adressat hat eine E-Mail Adresse hinterlegt

Zu 1:
<img width="1096" alt="image" src="https://github.com/openjverein/jverein/assets/63780296/dfa2254a-eaa0-46eb-9f1c-4bbedaf24434">

Zu 2:
<img width="1003" alt="image" src="https://github.com/openjverein/jverein/assets/63780296/363c1988-a969-4076-b584-c25c6feae0f4">

2024-01-29 11:32 UTC, MSchmalzl commented
> Die Spendenbescheinigung wird der E-Mail **nicht** als Anhang angefügt. Ich bin noch am überlegen ob das möglich/sinnvoll ist.

Ich hätte es auf den ersten Blick erwartet. Allerdings gibt es beim elektronischen übermitteln von Spendenbescheinigungen halt ein paar Voraussetzungen zu beachten. Würde das von daher erst mal nicht interpretieren.

2024-01-29 15:53 UTC, MSchmalzl commented
Ich habe also folgende Buchung:
![SpendeBuchung](https://github.com/openjverein/jverein/assets/143084339/11e60d2a-db4b-4938-ad6f-4c14d1ca9df3)

und klicke jetzt auf erstellen
![SpendeAutomatisch](https://github.com/openjverein/jverein/assets/143084339/3ecba914-8360-43ef-a15d-d9c8ed6be32c)
sollte dann eine Spendenbescheinigung erstellt werden?

2024-01-29 16:41 UTC, MSchmalzl commented
Ja. Haken ist aktiviert. Habe schon vermutet, dass es am fehlenden Formular liegt. Ist halt nur etwas verwirrend. Man bekommt eine Erfolgsmeldung, es werden aber keine Bescheinigungen generiert.

Aber zurück zum eigentlichen PR. Das mit der E-Mail funktoniert und passt.

2024-01-29 16:41 UTC, MSchmalzl approved these changes

2024-01-31 09:54 UTC, willuhn commented
@dippeal Ich hatte mein Review schon gemacht und eine Anmerkung hinterlassen, die den Code etwas vereinfachen würde.

2024-01-31 10:13 UTC, willuhn requested changes

2024-01-31 10:44 UTC, MSchmalzl approved these changes

2024-01-31 10:44 UTC, merged