DSGVO konformes Löschen von Mitgliedern, implementiert #213
openjverein/jverein pull request #224
Opened 2024-05-05 08:08 UTC by JohannMaierhofer

Mit diesem Feature lassen sich Mitglieder DSGVO konform löschen (siehe Issue #213). Es werden alle Datensätze die auf das Mitglied verweisen ebenfalls gelöscht. Mails werden nur gelöscht wenn das Mitglied der einzige Empfänger war. Buchungen in den Konten bleiben erhalten, einerseits wegen der Aufbewahrungsfristen und andererseits weil sonst die Buchführung auch nicht mehr stimmen würde.
Der Löschen Dialog gibt eine entsprechende Warnung aus:
![Screenshot_20240505_094937](https://github.com/openjverein/jverein/assets/126261667/97ad628c-aefc-4fc2-ac94-d9a5805ba48c)

Zu den Änderungen:
- Bei allen Tabellen die das Mitglied referenzieren muss der Foreign Key auf CASCADE gesetzt werden. Das war nicht bei allen Tabellen der Fall. Die Änderung passiert im Migrationscode. 
- Bei Lastschrift habe ich auch die Referenz auf Kursteilnehmer auf CASCADE gesetzt damit man auch die löschen kann.
- Da Buchungen erhalten bleiben sollen werden hier die Referenzen auf Spendenbescheinigung und Mitgliedskonto (Sollbuchung) auf SET NULL konfiguriert. Damit habe ich auch die überschriebene Methode delete bei der SpendenbescheinigungImpl gelöscht weil das nicht mehr explizit nötig ist.
- Im Delete Dialog gebe ich den Warning Text und Icon aus. Siehe Bild oben.
- Da Mails nicht implizit gelöscht werden habe ich dies im Java Code implementiert. Mails an das Mitglied werden nur gelöscht wenn das Mitglied der einzige Empfänger ist. Bei den anderen Mails wird das Mitglied implizit (wegen CASCADE) aus der Empfängerliste gelöscht.

PS: Foreign Keys kann man nicht modifizieren sondern muss sie erst löschen und wieder neu erzeugen. Ich habe in AbstractDDLUpdate die Methode zum Löschen des Foreign Key implementiert. Das funktioniert bei h2db und MySql unterschiedlich.
Ich konnte nur die Implementierung für h2db testen. Wer die MySql hat sollte schauen ob es auch dort funktioniert.

2024-07-18 17:52 UTC, SchachtnerTh commented
Wie hast Du das eigentlich mit MySQL getestet? Ich arbeite mit meiner Live-Umgebung mit einer MySQL-Datenbank und würde gerne mit Klonen dieser Datenbank hier arbeiten. Dann brauch ich nicht immer Test-Mitglieder anzulegen. Gibt es denn eine Möglichkeit, beim Debuggen statt mit der H2-Datenbank mit einer MySQL-Datenbank zu arbeiten? Ich hab das mit dieser Anleitung versucht. In der Live-Umgebung hat das funktioniert, bei meinen Tests hier funktioniert das nicht: https://doku.jverein.de/allgemein/mysql-support

2024-07-18 18:06 UTC, SchachtnerTh commented
Wie kann ich die DSGVO-konforme Löschfunktion finden?
Wenn ich auf "Löschen" klicke, wird mir folgender Dialog angezeigt: 
![image](https://github.com/user-attachments/assets/8177de7b-56db-41dc-acf4-588ceba8381f)

Klicke ich da "Ja", wird mir das hier angezeigt:
![image](https://github.com/user-attachments/assets/e4aa26f5-5822-4baa-8382-3fa521984c00)

Folgende Fehlermeldung wird angezeigt:
Fehler beim Löschen des Mitgliedes
java.rmi.RemoteException: delete failed, rollback successful; nested exception is: 
	org.h2.jdbc.JdbcSQLIntegrityConstraintViolationException: Referentielle Integrität verletzt: "FKBUCHUNG3: PUBLIC.BUCHUNG FOREIGN KEY(MITGLIEDSKONTO) REFERENCES PUBLIC.MITGLIEDSKONTO(ID) (2)"
Referential integrity constraint violation: "FKBUCHUNG3: PUBLIC.BUCHUNG FOREIGN KEY(MITGLIEDSKONTO) REFERENCES PUBLIC.MITGLIEDSKONTO(ID) (2)"; SQL statement:
delete from MITGLIED where ID = 2 [23503-199]
	at de.willuhn.datasource.db.AbstractDBObject.delete(AbstractDBObject.java:390)
	at de.jost_net.JVerein.gui.action.MitgliedDeleteAction.handleAction(MitgliedDeleteAction.java:63)
	at de.willuhn.jameica.gui.parts.ContextMenu$1.handleEvent(ContextMenu.java:184)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5855)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1529)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:5065)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4517)
	at de.willuhn.jameica.gui.GUI.loop(GUI.java:938)
	at de.willuhn.jameica.gui.GUI.init(GUI.java:335)
	at de.willuhn.jameica.system.Application.init(Application.java:145)
	at de.willuhn.jameica.system.Application.newInstance(Application.java:87)
	at de.willuhn.jameica.Main.main(Main.java:78)
Caused by: org.h2.jdbc.JdbcSQLIntegrityConstraintViolationException: Referentielle Integrität verletzt: "FKBUCHUNG3: PUBLIC.BUCHUNG FOREIGN KEY(MITGLIEDSKONTO) REFERENCES PUBLIC.MITGLIEDSKONTO(ID) (2)"
Referential integrity constraint violation: "FKBUCHUNG3: PUBLIC.BUCHUNG FOREIGN KEY(MITGLIEDSKONTO) REFERENCES PUBLIC.MITGLIEDSKONTO(ID) (2)"; SQL statement:
delete from MITGLIED where ID = 2 [23503-199]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:457)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.constraint.ConstraintReferential.checkRow(ConstraintReferential.java:373)
	at org.h2.constraint.ConstraintReferential.checkRowRefTable(ConstraintReferential.java:390)
	at org.h2.constraint.ConstraintReferential.checkRow(ConstraintReferential.java:265)
	at org.h2.table.Table.fireConstraints(Table.java:1020)
	at org.h2.table.Table.fireAfterRow(Table.java:1038)
	at org.h2.command.dml.Delete.update(Delete.java:129)
	at org.h2.constraint.ConstraintReferential.updateWithSkipCheck(ConstraintReferential.java:424)
	at org.h2.constraint.ConstraintReferential.checkRowRefTable(ConstraintReferential.java:395)
	at org.h2.constraint.ConstraintReferential.checkRow(ConstraintReferential.java:265)
	at org.h2.table.Table.fireConstraints(Table.java:1020)
	at org.h2.table.Table.fireAfterRow(Table.java:1038)
	at org.h2.command.dml.Delete.update(Delete.java:129)
	at org.h2.command.CommandContainer.update(CommandContainer.java:133)
	at org.h2.command.Command.executeUpdate(Command.java:267)
	at org.h2.jdbc.JdbcStatement.executeUpdateInternal(JdbcStatement.java:169)
	at org.h2.jdbc.JdbcStatement.executeUpdate(JdbcStatement.java:126)
	at de.willuhn.datasource.db.AbstractDBObject.delete(AbstractDBObject.java:372)
	... 12 more

2024-07-18 19:28 UTC, JohannMaierhofer commented
Ich habe auch mit MySQL getestet. In der Beschreibung im Online Help ist leider etwas abgeschnitten. Ich habe folgendes in der Datei de.jost_net.JVerein.rmi.JVereinDBService.properties:

database.driver=de.jost_net.JVerein.server.DBSupportMySqlImpl
database.driver.mysql.jdbcurl=jdbc\:mysql\://localhost\:3306/jverein?useUnicode\=Yes
#&characterEncoding\=ISO8859_1
database.driver.mysql.username='jverein'
database.driver.mysql.password=jverein
database.driver.mysql.scriptprefix=mysql-database.driver.mysql.jdbcdriver=org.mariadb.jdbc.Driver

Das hatte ich irgendwo anders gefunden. Die letzte Zeile ist in der Help abgeschnitten. Ich habe die Maria DB.

Bezüglich deinem Problem. Du hast wohl nicht die SW aus meinem Branch. Denn sonst sollte beim Delete mein neuer Dialog kommen.

2024-07-19 04:55 UTC, SchachtnerTh commented
Ja stimmt. Als ich es das erste Mal ausprobiert habe, lief irgendwie noch der alte Code. Jetzt habe ich aber Deinen Code.
Der Fehler tritt bei mir in Zeile 117 auf:
![image](https://github.com/user-attachments/assets/1a0ef65a-981a-4c45-9c03-a22623bba268)

Es scheint, dass der Fehler in der Datei AbstractDBObject.java auftritt, für die ich aber grad keine Quelltexte habe.
Wahrscheinlich mach ich wieder nur irgendwas falsch ;-)

2024-07-19 06:02 UTC, JohannMaierhofer commented
Das ist seltsam. Kannst du mal schauen ob die Datenbank Migration 440 auch durchgeführt wurde. Also, ob der aktuelle Stand der Datenbank aif 440 steht. Das müsste im JVerein About Dialog stehen.

2024-07-19 06:59 UTC, SchachtnerTh commented
Nein, da steht jetzt 437. Wieso auch immer:
![image](https://github.com/user-attachments/assets/59e9cd79-3476-4e7d-8c1c-f257e3c94a2f)

Die Datei ist aber da:
![image](https://github.com/user-attachments/assets/1fe5e4c2-0162-4faf-8b4a-086270bcda9f)

Hier noch ein Auszug aus dem Log. Auch hier geht die Zählung nur bis 437.
Ich weiß aber nicht, ob das Stoppen des DB-Dienstes so stimmt oder nicht:

[Fri Jul 19 08:55:27 CEST 2024][INFO][main][de.willuhn.jameica.gui.SplashScreen$3.run]  JVerein-DB-Update: 436 ...
[Fri Jul 19 08:55:27 CEST 2024][INFO][main][de.jost_net.JVerein.server.DDLTool.AbstractDDLUpdate.setNewVersion] JVerein-DB-Update: 436
[Fri Jul 19 08:55:27 CEST 2024][INFO][main][de.willuhn.sql.ScriptExecutor.execute] starting transaction
[Fri Jul 19 08:55:27 CEST 2024][INFO][main][de.willuhn.sql.ScriptExecutor.execute] commit transaction
[Fri Jul 19 08:55:27 CEST 2024][INFO][main][de.willuhn.jameica.gui.SplashScreen$3.run]  JVerein-DB-Update: 437 ...
[Fri Jul 19 08:55:27 CEST 2024][INFO][main][de.jost_net.JVerein.server.DDLTool.AbstractDDLUpdate.setNewVersion] JVerein-DB-Update: 437
[Fri Jul 19 08:55:27 CEST 2024][INFO][main][de.willuhn.datasource.db.DBServiceImpl.stop] stopping db service
[Fri Jul 19 08:55:27 CEST 2024][INFO][main][de.willuhn.datasource.db.DBServiceImpl.closeConnection] commit connection
[Fri Jul 19 08:55:27 CEST 2024][INFO][main][de.willuhn.datasource.db.DBServiceImpl.closeConnection] closing connection
[Fri Jul 19 08:55:27 CEST 2024][INFO][main][de.willuhn.datasource.db.DBServiceImpl.closeConnection] connection closed
[Fri Jul 19 08:55:27 CEST 2024][INFO][main][de.willuhn.datasource.db.DBServiceImpl.stop] db service stopped [1 connection(s) closed]
[Fri Jul 19 08:55:27 CEST 2024][INFO][main][de.willuhn.jameica.services.ArchiveService.init] checking jameica.messaging availability
[Fri Jul 19 08:55:27 CEST 2024][INFO][main][de.willuhn.jameica.messaging.LookupService.lookup] performing multicast lookup for service name: tcp:de.willuhn.jameica.messaging.Plugin.connector.tcp
[Fri Jul 19 08:55:32 CEST 2024][INFO][main][de.willuhn.jameica.messaging.LookupService.lookup] no server found for service name: tcp:de.willuhn.jameica.messaging.Plugin.connector.tcp
[Fri Jul 19 08:55:32 CEST 2024][WARN][main][de.willuhn.jameica.services.ArchiveService.init] no archive server found
[Fri Jul 19 08:55:32 CEST 2024][ERROR][main][de.willuhn.jameica.plugin.Version.parse] unparsable version part: [VERSION]

2024-07-19 07:12 UTC, SchachtnerTh commented
Wenn ich die Migration in 438 umbenenne, klappt alles.

2024-07-19 07:26 UTC, JohannMaierhofer commented
> Wenn ich die Migration in 438 umbenenne, klappt alles.

Dann hast du aber nicht wirklich den aktuellen Stand der SW. Es existieren ja auch die Migrationen 438 und 439. 440 war darum schon richtig.
Da die Nummerierung fortlaufend ist wurde bei dir dann die 440 nicht ausgeführt.
Jetzt hast du ein Problem mit der eigentlichen Migration 438. Wenn es eine Test Datenbank war kannst du sie löschen. Ansonsten müsstest du mit einem Datenbank Editor die Version auf 437 zurücksetzen und dann die richtigen Migrationen machen. Die 440 doppelt ausführen sollte gehen.

2024-07-19 07:37 UTC, SchachtnerTh commented
Ganz verstehen tu ich das aber noch nicht. Ich habe einfach Deinen Branch ausgecheckt. Da sollte doch alles drin sein, oder? 

War eine Test-Datenbank, ja. Ist nix kaputt gegangen. 👍

Am 19. Juli 2024 09:27:06 MESZ schrieb Johann Maierhofer ***@***.***>:
>> Wenn ich die Migration in 438 umbenenne, klappt alles.
>
>Dann hast du aber nicht wirklich den aktuellen Stand der SW. Es existieren ja auch die Migrationen 438 und 439. 440 war darum schon richtig.
>Da die Nummerierung fortlaufend ist wurde bei dir dann die 440 nicht ausgeführt.
>Jetzt hast du ein Problem mit der eigentlichen Migration 438. Wenn es eine Test Datenbank war kannst du sie löschen. Ansonsten müsstest du mit einem Datenbank Editor die Version auf 437 zurücksetzen und dann die richtigen Migrationen machen. Die 440 doppelt ausführen sollte gehen. 
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/openjverein/jverein/pull/224#issuecomment-2238545067
>You are receiving this because you commented.
>
>Message ID: ***@***.***>
-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

2024-07-19 07:58 UTC, JohannMaierhofer commented
Das wahr wohl mein Problem. In meinem Branch haben die 438 und 439 gefehlt. Da bei mir die schon ausgeführt waren weil ich die entsprechenden Features die diese eingeführt haben schon benutzt hatte, ist das bei mir nicht aufgefallen.
Ich habe jetzt den aktuellen Stand aus dem Main in das Feature gemerged. Jetzt sind die anderen Migrationen auch dabei.

2024-07-19 10:00 UTC, SchachtnerTh commented on src/de/jost_net/JVerein/server/SpendenbescheinigungImpl.java
Ich verstehe diesen Teil nicht.
Ich vermute, dass die delete()-Methode jetzt nicht mehr benötigt wird, weil Verweise in der Datenbank jetzt durch das Löschen kaskadieren.
Aber wann wurde sie vorher aufgerufen. Ich habe die Stelle nicht gefunden.

2024-07-19 11:20 UTC, JohannMaierhofer commented on src/de/jost_net/JVerein/server/SpendenbescheinigungImpl.java
Die Methode gibt es weiterhin in der Oberkasse. Sie wird jetzt nur nicht mehr überschrieben. Die Methode wird aufgerufen wenn man eine Spendenbescheinigung löscht.
Der gelöschte Teil wird wie du schon vermutest nicht mehr gebraucht wegen der Änderung am Foreign Key der jetzt auf SET NULL steht. Damit setzt die Datenbank das Attribut auf null wenn man die Spendenbescheinigungen löscht. Mit der alten Definition hätte die Datenbank das Löschen verhindert. Darum müsste man den Wert per SW löschen.

2024-07-20 17:48 UTC, SchachtnerTh approved these changes

2024-07-21 06:17 UTC, willuhn commented
Der Feature-Wunsch in #213 kommt von @mbmueller - daher sollte er das Review durchführen.

2024-07-21 09:13 UTC, JohannMaierhofer commented
Du hast den MySQL Community Server. Im Trace steht org.mariadb.jdbc.client... 
Kann es sein, dass der Treiber nicht passt?

2024-07-21 09:40 UTC, JohannMaierhofer commented
Ja, man muss den Constraint löschen. Dann ist es aber bei MYSQL ganz anders als bei H2. Hier hat der Constraint den Namen "fk_sekundaerbeitragegruppe1".

![Bildschirmfoto_20240721_113659](https://github.com/user-attachments/assets/d5a4ac48-f3e1-48e1-9f48-d4d99bb1696d)

Jetzt schaue ich nochmal warum die Migration bei meinen Tests bei MariaDB funktioniert hat.

2024-07-21 09:54 UTC, JohannMaierhofer commented
Bei mir heißt auch der Constraint "fk_sekundaerbeitragegruppe1", allerdings ist das Bild von nach der Migration.

![Bildschirmfoto_20240721_115141](https://github.com/user-attachments/assets/36798b9f-8e2e-4561-86db-f296bc316ba4)

2024-07-21 10:15 UTC, JohannMaierhofer commented
Ich habe schon in einem Kommentar zu #223 geschrieben, dass ich glaube, dass der Befehl zum Generieren des Key im Code zu MySQL nicht ganz stimmt. Das denke ich führt jetzt zu diesem Fehler.
Ich kann jetzt im Code zwischen H2 und MySQL unterscheiden, aber wie unterscheide ich zwischen MariaDb und MySql? Scheinbar ist es da auch unterschiedlich.

2024-07-21 10:24 UTC, JohannMaierhofer commented
Hier noch einmal mein Kommentar zu #223. 


Ich habe mir hier das Create Statement aus der MySQL Dokumentation geholt.

ADD [CONSTRAINT [symbol]] FOREIGN KEY [index_name] (col_name,...)

So wie ich es verstanden habe ist symbol der Contraint Name und index_name der Name des Indexes der auf die Spalte erzeugt wurde.

Der aktuelle Code setzt bei MySQL den übergeben Contraint Namen als index_name ein. Das wäre aber falsch weil der Index einen anderen Namen hat.
Für das Löschen des Foreign Key muss man den symbol Namen nehmen.

DROP {CHECK | CONSTRAINT} symbol

Da der bei MySQL nicht angegeben ist wird er wohl automatisch generiert.
Dann funktioniert mein Upgrade440 nicht weil zum Löschen der übergebene Contraint Name benutzt wird.

Darum glaube ich, dass die Methode createForeignKey nicht stimmt.

Jetzt habe ich noch etwas gefunden. Die spec sagt:
For ALTER TABLE, unlike CREATE TABLE, ADD FOREIGN KEY ignores index_name if given and uses an automatically generated foreign key name. As a workaround, include the CONSTRAINT clause to specify the foreign key name:

Also wird wohl beim aktuellen Code der Contraint Name sowieso ignoriert und einer automatisch generiert. Es wäre aber wohl besser den Request zu ändern und den Namen als Symbol zu übergeben wie bei H2.

2024-07-21 11:23 UTC, mbmueller commented
> Der Feature-Wunsch in #213 kommt von @mbmueller - daher sollte er das Review durchführen.

Würde ich gerne. Habe im Moment aber keine Zeit, erst wieder Mitte August. Außerdem hat sich bei mir die IDE wieder zerschossen. Kann man das Projekt irgendwie mal abändern, dass das ohne großen Aufwand in IntelliJ läuft?

2024-07-21 11:29 UTC, JohannMaierhofer commented
@dippeal könntest du mir die Namen der Foreign Keys aus deiner Datenbank auflisten. Ich hoffe dann mal dass sie auch bei anderen dann so automatisch genereiert worden sind.
Den Code würde ich dann so ändern, dass ich zwischen H2 und MySql unterscheide. Bei MySql kann ich es erst mit den H2 Namen probieren wegen MariaDB und wenn es eine Exception gibt dann nehme ich die anderen Namen.

2024-07-21 11:37 UTC, JohannMaierhofer commented
Frage: Wo wird denn eigentlich beim ersten Start die neue leere Datenbasis erzeugt?

2024-07-22 05:59 UTC, JohannMaierhofer commented
Ich dachte nur an die, die in der Migrationen vorkommen.
Du musst das nicht mehr machen.
Ich habe vor auf einem zweiten PC eine MySQL Datenbank zu installieren, dann kann ich auch selbst testen ob es funktioniert. Und auch zukünftige Migrationen kann ich dann selbst testen.

2024-07-22 10:31 UTC, JohannMaierhofer commented
Ich habe jetzt die Änderung für MySql gemacht. Die unteschiedlichen Namen gab es nur bei dem eine Attribut. Das liegt wohl daran, dass sie automatisch generiert wurden. H2 und MariaDB benutzen da anscheinend den gleichen Algorithmus. Nur bei MySQL war der generierte Name anders.
Beim testen habe ich wie vermutet festgestellt, dass MySQL wieder neue Namen generiert und nicht die übergebenen benutzt. Damit wurden dann auch alle anderen Namen die bisher gleich waren bei MySql geändert.
Ich habe dann meinen Vorschlag implementiert und die createForeignKey Methode für MYSQL so geändert wie es bei H2 ist, also den Constraint Namen zwischen CONSTRAINT und FOREIGN KEY. Dann wurden auch die übergebenen Namen gesetzt und keine Namen automatisch generiert.
Ich habe das Ganze mit H2, MySQL und MariaDB getestet. Sowohl ein Upgrade von der Version 21 als auch mit einer neuen Datenbasis.

2024-07-22 11:16 UTC, JohannMaierhofer commented
> Update lief zwar durch, scheint aber nicht so sauber.

Warum, wegen des gleichen Namens wie der Index?

2024-07-22 11:23 UTC, JohannMaierhofer commented
> Wunderte mich, dass die sekundaerebeitragsgruppe_ibfk_2 nicht auch im neuen Namensschema ist.

Diesen Foreign Key habe ich ja nicht geändert.

2024-07-22 11:24 UTC, JohannMaierhofer commented
Ich werde jetzt trotzdem mal den Namen anders wählen als den Index. Ich weiß nicht ob das sonst Probleme bereiten könnte. Ich nehme wieder den alten Namen von H2.

2024-07-22 11:36 UTC, JohannMaierhofer commented
Ich habe jetzt das "_" reingemacht. Jetzt sind die Namen für Key und Constraint trotzdem gleich. Es übernimmt wohl den Constraint Namen als Schlüsselname.
Durch meine Änderung des createForeignKey wird jetzt der Constraint Name explizit gesetzt und der Schlüssel automatisch gesetzt. Früher war es umgekehrt.

2024-07-22 11:44 UTC, JohannMaierhofer commented
Musste noch Kleinschrift bei fk_sekundaerbeitragegruppe1 machen analog zu Upgrade0394.

Bei dieser Migration (Upgrade0394) wird übrigens der automatisch generierte Name bei MySql erzeugt. Wenn die Migration mit dem aktuellen Code läuft entsteht hier kein automatisch generierter Name mehr.

2024-07-23 16:19 UTC, JohannMaierhofer commented
Wegen der Migration muss erst #254 übernommen werden.

2024-07-26 12:53 UTC, lenilsas reviewed
Auch hier müssten eigentlich die Mitgliedsdokumente mit gelöscht werden und nicht nur die Einträge in der Datenbank.

2024-07-26 14:48 UTC, JohannMaierhofer commented
Du hast Recht, ich schaue mal wie das geht.

2024-07-27 07:42 UTC, JohannMaierhofer commented
Jetzt werden auch die Dokumente gelöscht. Ich habe das gleich analog auch bei den Buchungen gemacht. Damit funktioniert das DBBereinigen richtig.

2024-07-27 07:56 UTC, lenilsas approved these changes

2024-08-14 13:50 UTC, JohannMaierhofer commented
Ich löse den Mergekonflikt wenn noch jemand reviewt. Vorher lasse ich mal #296 Vorrang.

2024-08-20 11:25 UTC, JohannMaierhofer commented
Habe den Code auf aktuellen Stand gebracht (Merge Master) und Megre Konflikt wegen Upgrade0442 behoben.
Der Upgrade0443 ist gleich wie #296. Je achden wer erster übernommen wird muss ich den anderen dann anpassen.

2024-08-20 11:28 UTC, lenilsas approved these changes

2024-09-16 11:59 UTC, JohannMaierhofer commented
@mbmueller Hallo, wie schaut es mit deinem Review aus?
Der PR ist jetzt halt schon sehr lange bereit zur Übernahme. Es fehlt nur noch dein ok.

2024-09-18 15:44 UTC, mbmueller commented
Mach ich diese Woche.

2024-09-19 15:00 UTC, mbmueller requested changes
Bei mir war ein Löschen der Mitglieder in folgenden Fällen immer noch nicht möglich:
`Caused by: org.h2.jdbc.JdbcSQLIntegrityConstraintViolationException: Referentielle Integrität verletzt: "FKSPENDENBESCHEINIGUNG2: PUBLIC.SPENDENBESCHEINIGUNG FOREIGN KEY(MITGLIED) REFERENCES PUBLIC.MITGLIED(ID) (32247)"
Referential integrity constraint violation: "FKSPENDENBESCHEINIGUNG2: PUBLIC.SPENDENBESCHEINIGUNG FOREIGN KEY(MITGLIED) REFERENCES PUBLIC.MITGLIED(ID) (32247)"; SQL statement:`

`java.rmi.RemoteException: delete failed, rollback successful; nested exception is: 
	org.h2.jdbc.JdbcSQLIntegrityConstraintViolationException: Referentielle Integrität verletzt: "FKWIEDERVORLAGE1: PUBLIC.WIEDERVORLAGE FOREIGN KEY(MITGLIED) REFERENCES PUBLIC.MITGLIED(ID) (32247)"
Referential integrity constraint violation: "FKWIEDERVORLAGE1: PUBLIC.WIEDERVORLAGE FOREIGN KEY(MITGLIED) REFERENCES PUBLIC.MITGLIED(ID) (32247)"; SQL statement:`

`java.rmi.RemoteException: delete failed, rollback successful; nested exception is: 
	org.h2.jdbc.JdbcSQLIntegrityConstraintViolationException: Referentielle Integrität verletzt: "FKLASTSCHRIFT2: PUBLIC.LASTSCHRIFT FOREIGN KEY(MITGLIED) REFERENCES PUBLIC.MITGLIED(ID) (80956)"
Referential integrity constraint violation: "FKLASTSCHRIFT2: PUBLIC.LASTSCHRIFT FOREIGN KEY(MITGLIED) REFERENCES PUBLIC.MITGLIED(ID) (80956)"; SQL statement:`

Die Anmerkungen zum Code Style sind mir nur so nebenbei aufgefallen, da das im ganzen Projekt bisher so gehandhabt wurde, kann man die Diskussion aber gerne auch auslagern.

2024-09-19 15:00 UTC, mbmueller commented on src/de/jost_net/JVerein/gui/action/MitgliedDeleteAction.java
> +      final Mitglied m = (Mitglied) context;
Einzelne Buchstaben sind mMn keine guten Variablen Namen. Würde ich umbenenne zu bspw. `mitglied` oder `member`

2024-09-19 15:00 UTC, mbmueller commented on src/de/jost_net/JVerein/gui/action/MitgliedDeleteAction.java
>        YesNoDialog d = new YesNoDialog(YesNoDialog.POSITION_CENTER);
Varibale umbennen zu `dialog`

2024-09-19 15:00 UTC, mbmueller commented on src/de/jost_net/JVerein/gui/action/MitgliedDeleteAction.java
> +      DBIterator<MailEmpfaenger> it = Einstellungen.getDBService()
Umbennenen zu `iterator`

2024-09-19 15:00 UTC, mbmueller commented on src/de/jost_net/JVerein/gui/action/MitgliedDeleteAction.java
> +        Mail ma = ((MailEmpfaenger) it.next()).getMail();
Umbenennen zu `mail`

2024-09-19 15:00 UTC, mbmueller commented on src/de/jost_net/JVerein/gui/action/NichtMitgliedDeleteAction.java
>        YesNoDialog d = new YesNoDialog(YesNoDialog.POSITION_CENTER);
`dialog`

2024-09-19 15:00 UTC, mbmueller commented on src/de/jost_net/JVerein/gui/action/NichtMitgliedDeleteAction.java
> +      DBIterator<MailEmpfaenger> it = Einstellungen.getDBService()
`iterator`

2024-09-19 15:00 UTC, mbmueller commented on src/de/jost_net/JVerein/gui/action/NichtMitgliedDeleteAction.java
> +        Mail ma = ((MailEmpfaenger) it.next()).getMail();
`mail`

2024-09-19 19:13 UTC, JohannMaierhofer commented
Also wegen dem Code Style denke ich auch, dass ich mich da nur an die sonstigen Konventionen angepasst habe. Das könnte man in einer eigenen Diskussionsrunde besprechen und ein Code Style Guideline erstellen. Wenn es dir aber am Herzen liegt kann ich das natütirlich ändern.

Wegen der Exception glaube ich, das bei dir die Migration 443 aus diesem Branch nicht gelaufen ist. Kann es sein, dass du schon in die PRs 296 oder 315 geschaut hast. Wenn ja ist der Upgrade 443 von dort gelaufen und die DB steht jetzt bei dieser Nummer. Dann wird die Migration hier nicht mehr durchlaufen. Du müsstest im DB Editor die Version auf 442 zurücksetzen und dann neu starten. Falls die Migration gelaufen ist sollte deine Exception nicht passieren. In Upgrade0443 werden genau diese Attribute von RESTRICT auf CASCADE gesetzt.

2024-09-23 10:11 UTC, mbmueller approved these changes

2024-09-23 11:03 UTC, merged