Buchungsart übernehmen
openjverein/jverein pull request #465
Opened 2024-11-16 15:42 UTC by JohannMaierhofer

Dies implementiert #462. Es werden bei der Zuweisung einer Sollbuchung zur Buchung automatisch die Buchungsart und Buchungsaklasse in der Buchung gesetzt wenn sie noch null sind.

Ich habe die Änderung für den Sollbuchung Zuordnung Dialog (Aufruf aus dem Buchung Menü) implementiert und für die automatische Zuordnung.

Die automatische Zuordnung konnte ich aber nicht testen. In der Entwicklungsumgebung kommt es beim Zuordnen Button im zweiten Dialog zur Meldung:  "Es wird bereits eine Hintergrund-Aufgabe ausgeführt".
Dies liegt daran, dass der BuchungenSollbuchungZuordnungVorschauDialog in der Task des BuchungenSollbuchungZuordnungDialog aufgerufen wird. Beim Drücken des Buttons wird dann die zweite Hintergrund Task gestartet was zum Fehler führt. 

Das ganze passiert aber auch auf dem Main Branch ohne meine Änderung. Warum das außerhalb von Eclipse in den Standard Produktionen nicht auftritt weiß ich nicht. Evtl. ist da der BuchungenSollbuchungZuordnungVorschauDialog schneller geschlossen und die erste Task beendet bevor die zweite los läuft.

Schön ist aber eine solche Race Condition nicht. Kann man irgendwie den BuchungenSollbuchungZuordnungVorschauDialog aus der ersten Task starten ohne auf dessen Ende zu warten?

2024-11-16 15:55 UTC, JohannMaierhofer commented
Ich könnte aber auch die zweite Task entfernen

2024-11-16 16:20 UTC, JohannMaierhofer commented
Habe die zweite Task entfernt. Jetzt läuft es auch in Eclipse durch.

Dann hat noch ein Check auf null gefehlt.

2024-11-16 17:12 UTC, JohannMaierhofer commented
Ich habe jetzt die Methoden für Buchungsart bei Mitgliedkonto und Buchung korrigiert.

Werden die Ids benutzt dann steht das auch im getter und setter. Mich hat das immer verwirrt. Damit muss man bei den Checks und Zuweisungen nur die Ids benutzen und keine Objekte erzeugen.

2024-11-17 14:28 UTC, mbmueller approved these changes

2024-11-17 14:28 UTC, mbmueller commented on src/de/jost_net/JVerein/gui/dialogs/BuchungenSollbuchungZuordnungVorschauDialog.java
> -        try
Wieso wurde der try-Block ausgeweitet? Je kürzer der try-Block (und je näher am Statement, dass die Exception auslösen könnte) desto besser.

2024-11-17 15:04 UTC, mbmueller requested changes
Bei mir wird über das Kontextmenü keine Zuordnung der Buchungsart vorgenommen.

2024-11-17 15:17 UTC, JohannMaierhofer commented
> Bei mir wird über das Kontextmenü keine Zuordnung der Buchungsart vorgenommen.

Also bei mir schon. Es wird allerdings nur übernommen wenn noch keine gesetzt ist. Kannst du mal schauen ob sie wirklich noch nicht gesetzt ist. Und dann muss natürlich in der Sollbuchung die zugewiesen wird eine Buchungsart gesetzt sein.

2024-11-17 15:22 UTC, JohannMaierhofer commented on src/de/jost_net/JVerein/gui/dialogs/BuchungenSollbuchungZuordnungVorschauDialog.java
> -        try
Ich habe da nichts ausgeweitet. Das schaut nur im Diff so aus. Wenn du dir den ganzen Source Code anschaust wirst du es sehen.

2024-11-17 16:18 UTC, mbmueller commented
> > Bei mir wird über das Kontextmenü keine Zuordnung der Buchungsart vorgenommen.
> 
> Also bei mir schon. Es wird allerdings nur übernommen wenn noch keine gesetzt ist. Kannst du mal schauen ob sie wirklich noch nicht gesetzt ist. Und dann muss natürlich in der Sollbuchung die zugewiesen wird eine Buchungsart gesetzt sein.

Habe jetzt Buchung und Sollbuchung nochmal komplett neu angelegt und jetzt geht es. Auch bei anderen Buchungen geht es, scheint dann wohl ein Bug bei genau dieser Kombination gewesen zu sein. Kann ich aber jetzt auch nicht mehr reproduzieren.

2024-11-17 16:19 UTC, mbmueller approved these changes

2024-11-17 16:38 UTC, JohannMaierhofer commented
> > > Bei mir wird über das Kontextmenü keine Zuordnung der Buchungsart vorgenommen.
> > 
> > 
> > Also bei mir schon. Es wird allerdings nur übernommen wenn noch keine gesetzt ist. Kannst du mal schauen ob sie wirklich noch nicht gesetzt ist. Und dann muss natürlich in der Sollbuchung die zugewiesen wird eine Buchungsart gesetzt sein.
> 
> Habe jetzt Buchung und Sollbuchung nochmal komplett neu angelegt und jetzt geht es. Auch bei anderen Buchungen geht es, scheint dann wohl ein Bug bei genau dieser Kombination gewesen zu sein. Kann ich aber jetzt auch nicht mehr reproduzieren.

Ich sehe auch manchmal seltsame Dinge. Das liegt wahrscheinlich daran, dass Eclipse oft beim Umschalten von Repositories oder Branches nicht alle Fileänderungen mitbekommt oder der Compiler meint, dass er eine Datei nicht übersetzen muss. Ich mache dann auch mal Neustarts und Project Clean.

2024-11-17 20:43 UTC, lenilsas approved these changes

2024-11-17 20:43 UTC, merged