Spendenbescheinigung auf Zahler ausstellen
openjverein/jverein pull request #493
Opened 2024-11-26 13:27 UTC by JohannMaierhofer

Implementiert #439  entsprechend dem Konzept aus #467.

Ich habe jetzt ein Attribut Zahler in die Sollbuchung aufgenommen. Beim Abrechnungslauf wird dort der Zahler eingetragen. Beim Generieren der Spendenbescheinigung wird nach dem Zahler gesucht und dieser in die Spendenbescheinigung eingetragen.

 Hat der Zahler einen alternativen Kontoinhaber werden die Daten dieses Kontoinhabers in die Spendenbescheinigung übernommen, der Zahler wird nicht in der Spendenbescheinigung gesetzt da er ja der alternative Kontoinhaber als Mitglied nicht existiert. Es gibt ja auch jetzt schon Spendenbescheinigungen wo kein Mitglied eingetragen ist (Sachspenden).

Folgende GUI Änderungen habe ich gemacht:
- Bei der Sollbuchungen Liste wird der Zahler angezeigt
- In der Liste kann man auch nach Zahler filtern aber nur entweder Zahler oder Mitglied
- Bei Solbuchung Details wird der Zahler angezeigt und ist editierbar
- In der Spendenbescheinigung Liste habe ich die Spalten Spender und Spendenart hinzugefügt
-  In der Spendenbescheinigung Liste habe ich Name in Zeile 2 geändert, der Filter wirkt auf Zeile 2 und nicht beim Spender so wie bisher. Es könnte ja auch kein Spender eingetragen sein
- In der Spendenbescheinigung Detail zeige ich den Spender(Mitglied) an wenn er gesetzt ist, nicht editierbar

Da man einen Zahler löschen kann habe ich geändert, dass die zugehörigen Spendenbescheinigungen nicht mehr gelöscht werden. Ist der Zahler nicht das Mitglied bleibt ja die Sollbuchung bestehen und man könnte eine neue Spendenbescheinigung auf ein anderes Mitglied ausstellen weil ja die Buchung und Sollbuchung erhalten bleiben. Es schadet auch nicht wenn sie bestehen bleiben, es gilt ja auch bei elektonischen Spendenbescheinigungen eine Aufbewahrungsfrist.

Das Problem, dass man den alternativen Kontoinhaber ändern kann und dann bei der Generierung der Spendenbescheinigung evtl. den falschen kopiert ist hier nicht gelöst. Für eine Lösung müsste man die Daten des alternativen Kontoinhabers in der Sollbuchung speichern. Wenn das jemand will muss er einen eigenen Issue schreiben.
Es gibt folgende Workarounds:
- Vor Wechsel des alternativen Kontoinhabers die Spendenbescheinigungen erzeugen
- Die Spendenbescheinigungen editieren und einen anderen Namen eintragen
- Die Idee mit dem Familienverband funktioniert nicht bei Nicht-Mitglied Zahlern. Man könnte aber nach der Generierung der Sollbuchung dort manuell ein Nicht-Mitglied als Zahler eintragen.

Es ist so, dass man nach Generierung der Spendenbescheinigung noch den Spender in der Sollbuchung ändern kann. Ich habe das nicht verhindert, evtl. gibt es ja einen Anwendungsfall. Für bestehende Spendenbescheinigungen ist das ja egal weil dort ja der Zahler gespeichert ist. Darum sehe ich es auch als kein Problem an, eine Buchung mit Spendenbescheinigung einer andern Sollbuchung zuzuordnen.

Als letztes stellt sich mir noch die Frage wie das eigentlich bei den Rechnungen sein soll. Sollten die dann nicht auch auf den Zahler ausgestellt werden? Der muss ja eine Betrag zahlen und nicht das Mitglied und es wird ja auch bei ihm abgebucht. Wenn also zwei Beträge beim Zahle abgebucht werden sollten auch beide auf der Rechnung stehen. Das sollte man dann mit einem eigenen PR machen.

2024-11-26 19:30 UTC, JohannMaierhofer commented
Bezüglich des Änderns der Sollbuchung bei einer Buchung denke ich muss ein Check gemacht werden ob die aktuelle oder neue Sollbuchung in einer Rechnung ist. In dem Fall darf die Änderung nicht gemacht werden weil die Buchungen ja Teil der Rechnung sind.

2024-11-26 20:37 UTC, JohannMaierhofer commented
Ich habe noch geändert, dass über den Sollbuchung Zuordnen Dialog nach dem Zahler gesucht wird. Dieser hat ja die Buchung bezahlt. Damit findet man Sollbuchungen die er selbst bezahlt und auch die, die er für andere bezahlt.

2024-11-28 14:18 UTC, lenilsas commented on src/de/jost_net/JVerein/Queries/SollbuchungQuery.java
> +      sql.append(
Das finde ich nicht richtig. Ich denke eine Gutschrift ist kein Fehlbetrag sondern eine Überzahlung. Es wird ja vom Mitglied aus geschaut, ob es etwas zahlen muss oder eine Erstattung bekommen soll. Der Code sollte so sein:
```
if (DIFFERENZ.FEHLBETRAG == diff)
    {
      sql.append(" HAVING SUM(buchung.betrag) < mitgliedskonto.betrag OR "
          + "(SUM(buchung.betrag) IS NULL AND mitgliedskonto.betrag > 0)");
    }
    if (DIFFERENZ.UEBERZAHLUNG == diff)
    {
      sql.append(" HAVING SUM(buchung.betrag) > mitgliedskonto.betrag OR "
        + "(SUM(buchung.betrag) IS NULL AND mitgliedskonto.betrag < 0)");
    }
```

2024-11-28 14:52 UTC, JohannMaierhofer commented on src/de/jost_net/JVerein/Queries/SollbuchungQuery.java
> +      sql.append(
Ok, aus dieser Sichtweise hast du Recht. Dann ändere ich das.

2024-11-28 15:17 UTC, JohannMaierhofer commented on src/de/jost_net/JVerein/Queries/SollbuchungQuery.java
> +      sql.append(
Habe es geändert.

2024-12-02 21:36 UTC, lenilsas commented
> Hat der Zahler einen alternativen Kontoinhaber werden die Daten dieses Kontoinhabers in die Spendenbescheinigung übernommen, der Zahler wird nicht in der Spendenbescheinigung gesetzt da er ja der alternative Kontoinhaber als Mitglied nicht existiert. Es gibt ja auch jetzt schon Spendenbescheinigungen wo kein Mitglied eingetragen ist (Sachspenden).
> 
> Folgende GUI Änderungen habe ich gemacht:
> 
> * Bei der Sollbuchungen Liste wird der Zahler angezeigt
> * In der Liste kann man auch nach Zahler filtern aber nur entweder Zahler oder Mitglied

Müssen das hier zwei Felder sein? könnte man nicht auch gleichzeitig in beiden Felder Suchen? Ich denke das könnte verwirren wenn nur das eine oder das andere Feld verwendet werden darf.

> * Bei Solbuchung Details wird der Zahler angezeigt und ist editierbar

Ich frage mich, wie Sinnvoll das Bearbeiten und manuelle erstellen von Sollbuchungen insgesamt ist. Normalerweise sollten Sollbuchungen über einen Abrechnungslauf erstellt werden, alle angaben dazu Liegen in den Mitgliedsdaten. Nur in Ausnahmefällen müssen die Sollbuchungen manuell angepasst werden. Vor allem bei Lastschriften kann das zu Verwirrungen führen da diese ja nur beim Abrechnungslauf generiert werden jedoch nicht beim anlegen und bearbeiten von Sollbuchungen. Eventuell wäre ein Freischalten in den Einstellungen Sinnvoll.
Gehört nicht in diesen PR, fällt mir nur gerade auf...

> * In der Spendenbescheinigung Liste habe ich die Spalten Spender und Spendenart hinzugefügt
> * In der Spendenbescheinigung Liste habe ich Name in Zeile 2 geändert, der Filter wirkt auf Zeile 2 und nicht beim Spender so wie bisher. Es könnte ja auch kein Spender eingetragen sein
> * In der Spendenbescheinigung Detail zeige ich den Spender(Mitglied) an wenn er gesetzt ist, nicht editierbar
> 
> Da man einen Zahler löschen kann habe ich geändert, dass die zugehörigen Spendenbescheinigungen nicht mehr gelöscht werden. Ist der Zahler nicht das Mitglied bleibt ja die Sollbuchung bestehen und man könnte eine neue Spendenbescheinigung auf ein anderes Mitglied ausstellen weil ja die Buchung und Sollbuchung erhalten bleiben. Es schadet auch nicht wenn sie bestehen bleiben, es gilt ja auch bei elektonischen Spendenbescheinigungen eine Aufbewahrungsfrist.

Beim Löschen von Mitgliedern müsste dann die Meldung geändert werden, hier steht noch mit drin das Spendenbescheinigungen gelöscht werden.
Irgendwie ist das Inkonsistent, wenn man Spendenbescheinigungen für Mitglieder erstellen und dann die Mitglieder löschen kann (und somit kein Mitglied mehr zugeordnet ist), das Manuelle erstellen von Spendenbescheinigungen ohne dass ein Mitglied existiert aber nicht möglich ist.

> 
> Das Problem, dass man den alternativen Kontoinhaber ändern kann und dann bei der Generierung der Spendenbescheinigung evtl. den falschen kopiert ist hier nicht gelöst. Für eine Lösung müsste man die Daten des alternativen Kontoinhabers in der Sollbuchung speichern. Das wäre #439. Es gibt folgende Workarounds:
> 
> * Vor Wechsel des alternativen Kontoinhabers die Spendenbescheinigungen erzeugen

Das denke ich wäre der beste Weg. So oft sollte das ja nicht wechseln. In der Doku sollten wir darauf hinweisen. Auch beim automatischen erstellen sollte der Anwender immer prüfen ob die Ausgabe korrekt ist, alle fälle können wir nicht mit Tests abdecken.

> * Die Spendenbescheinigungen editieren und einen anderen Namen eintragen
> * Die Idee mit dem Familienverband funktioniert nicht bei Nicht-Mitglied Zahlern. Man könnte aber nach der Generierung der Sollbuchung dort manuell ein Nicht-Mitglied als Zahler eintragen.
> 
> Es ist so, dass man nach Generierung der Spendenbescheinigung noch den Spender in der Sollbuchung ändern kann. Ich habe das nicht verhindert, evtl. gibt es ja einen Anwendungsfall. Für bestehende Spendenbescheinigungen ist das ja egal weil dort ja der Zahler gespeichert ist. Darum sehe ich es auch als kein Problem an, eine Buchung mit Spendenbescheinigung einer andern Sollbuchung zuzuordnen.
> 
> Als letztes stellt sich mir noch die Frage wie das eigentlich bei den Rechnungen sein soll. Sollten die dann nicht auch auf den Zahler ausgestellt werden? Der muss ja eine Betrag zahlen und nicht das Mitglied und es wird ja auch bei ihm abgebucht. Wenn also zwei Beträge beim Zahle abgebucht werden sollten auch beide auf der Rechnung stehen. Das sollte man dann mit einem eigenen PR machen.

Ja das stimmt. Hier würde ich es dann auch so machen, dass der Zahler verwendet wird, bei einem abweichenden Kontoinhaber aber nur seine Daten in der Rechnung verwendet werden und es trotzdem dem Mitglied zugeordnet bleibt.
Dabei ist mir aufgefallen, dass die Mailadresse es abweichenden Kontoinhabers nur bei denLastschriften eingetragen wird und somit auch nur beim Versand von Prenotifications verwendet wird. Eigentlich müsste die ja auch bei den Spendenbescheinigungen und den Rechnungen verwendet werden.
Insgesamt bin ich mir beim abweichendem Kontoinhaber unsicher und ich denke es gibt mehrere mögliche Anwendungsfälle:
-Alles wird an das Mitglied geschickt, nur das Konto gehört jemandem anderen, hier wäre evtl. eine Rechnungskopie an den Kontoinhaber sinnvoll, am besten auf der Originalrechnung ein Vermerk wer bezahlt.
-vor allem bei Kindern ist das Kind Mitglied aber Kontoinhaber und Rechnungsempfänger sind die Eltern

2024-12-03 07:55 UTC, JohannMaierhofer commented
> > Hat der Zahler einen alternativen Kontoinhaber werden die Daten dieses Kontoinhabers in die Spendenbescheinigung übernommen, der Zahler wird nicht in der Spendenbescheinigung gesetzt da er ja der alternative Kontoinhaber als Mitglied nicht existiert. Es gibt ja auch jetzt schon Spendenbescheinigungen wo kein Mitglied eingetragen ist (Sachspenden).
> > 
> > Folgende GUI Änderungen habe ich gemacht:
> > 
> > * Bei der Sollbuchungen Liste wird der Zahler angezeigt
> > * In der Liste kann man auch nach Zahler filtern aber nur entweder Zahler oder Mitglied
> 
> Müssen das hier zwei Felder sein? könnte man nicht auch gleichzeitig in beiden Felder Suchen? Ich denke das könnte verwirren wenn nur das eine oder das andere Feld verwendet werden darf.
> 

Ja, es sind zwei Felder. Ich hätte schreiben sollen "der Zahler zusätzlich angezeigt" 
Bei gleichzeitig suchen wusste ich nicht wie ich das machen sollte. Ich mache ein join von der Mitgliedskonto Tabelle mit dem Mitglied. Da nutze ich entweder mitgliedskonto.mitglied ist mitglied.id oder eben mitgliedkonto.zahler. Kann man da beim join mit OR beide Bedingungen angeben? Ich probierst mal. 


> > * Bei Solbuchung Details wird der Zahler angezeigt und ist editierbar
> 
> Ich frage mich, wie Sinnvoll das Bearbeiten und manuelle erstellen von Sollbuchungen insgesamt ist. Normalerweise sollten Sollbuchungen über einen Abrechnungslauf erstellt werden, alle angaben dazu Liegen in den Mitgliedsdaten. Nur in Ausnahmefällen müssen die Sollbuchungen manuell angepasst werden. Vor allem bei Lastschriften kann das zu Verwirrungen führen da diese ja nur beim Abrechnungslauf generiert werden jedoch nicht beim anlegen und bearbeiten von Sollbuchungen. Eventuell wäre ein Freischalten in den Einstellungen Sinnvoll.
> Gehört nicht in diesen PR, fällt mir nur gerade auf...

Nachdem man aber Sollbuchungen auch manuell erstellen kann muss mann editieren können. Da sollten wir weiter nachdenken. Evtl. Ein Flag in der Sollbuchung ob manuell oder automatisch erzeugt. 

> 
> > * In der Spendenbescheinigung Liste habe ich die Spalten Spender und Spendenart hinzugefügt
> > * In der Spendenbescheinigung Liste habe ich Name in Zeile 2 geändert, der Filter wirkt auf Zeile 2 und nicht beim Spender so wie bisher. Es könnte ja auch kein Spender eingetragen sein
> > * In der Spendenbescheinigung Detail zeige ich den Spender(Mitglied) an wenn er gesetzt ist, nicht editierbar
> > 
> > Da man einen Zahler löschen kann habe ich geändert, dass die zugehörigen Spendenbescheinigungen nicht mehr gelöscht werden. Ist der Zahler nicht das Mitglied bleibt ja die Sollbuchung bestehen und man könnte eine neue Spendenbescheinigung auf ein anderes Mitglied ausstellen weil ja die Buchung und Sollbuchung erhalten bleiben. Es schadet auch nicht wenn sie bestehen bleiben, es gilt ja auch bei elektonischen Spendenbescheinigungen eine Aufbewahrungsfrist.
> 
> Beim Löschen von Mitgliedern müsste dann die Meldung geändert werden, hier steht noch mit drin das Spendenbescheinigungen gelöscht werden.

Ja, das muss ich ändern. 

> Irgendwie ist das Inkonsistent, wenn man Spendenbescheinigungen für Mitglieder erstellen und dann die Mitglieder löschen kann (und somit kein Mitglied mehr zugeordnet ist), das Manuelle erstellen von Spendenbescheinigungen ohne dass ein Mitglied existiert aber nicht möglich ist.
> 

Doch, man kann Sachspendenbescheinigungen in der Liste mit dem Button unten ohne Mitglied erzeugen. Aber ja, bei Geldspenden haben wir das nicht. Eigentlich ist das inkonsistent. Sachspenden sollten auch durch eine Buchung hinterlegt sein. 

Mit Spendenbescheinigung ohne Mitglied sehe ich kein Problem. Der Name steht ja immer noch drinnen. Das ist wie bei Buchung, die bleiben ja auch erhalten. Und wegen der Aufbewahrungsfristen macht es ja Sinn diese zu behalten. 



> > 
> > Das Problem, dass man den alternativen Kontoinhaber ändern kann und dann bei der Generierung der Spendenbescheinigung evtl. den falschen kopiert ist hier nicht gelöst. Für eine Lösung müsste man die Daten des alternativen Kontoinhabers in der Sollbuchung speichern. Das wäre #439. Es gibt folgende Workarounds:
> > 
> > * Vor Wechsel des alternativen Kontoinhabers die Spendenbescheinigungen erzeugen
> 
> Das denke ich wäre der beste Weg. So oft sollte das ja nicht wechseln. In der Doku sollten wir darauf hinweisen. Auch beim automatischen erstellen sollte der Anwender immer prüfen ob die Ausgabe korrekt ist, alle fälle können wir nicht mit Tests abdecken.
> 
> > * Die Spendenbescheinigungen editieren und einen anderen Namen eintragen
> > * Die Idee mit dem Familienverband funktioniert nicht bei Nicht-Mitglied Zahlern. Man könnte aber nach der Generierung der Sollbuchung dort manuell ein Nicht-Mitglied als Zahler eintragen.
> > 
> > Es ist so, dass man nach Generierung der Spendenbescheinigung noch den Spender in der Sollbuchung ändern kann. Ich habe das nicht verhindert, evtl. gibt es ja einen Anwendungsfall. Für bestehende Spendenbescheinigungen ist das ja egal weil dort ja der Zahler gespeichert ist. Darum sehe ich es auch als kein Problem an, eine Buchung mit Spendenbescheinigung einer andern Sollbuchung zuzuordnen.
> > 
> > Als letztes stellt sich mir noch die Frage wie das eigentlich bei den Rechnungen sein soll. Sollten die dann nicht auch auf den Zahler ausgestellt werden? Der muss ja eine Betrag zahlen und nicht das Mitglied und es wird ja auch bei ihm abgebucht. Wenn also zwei Beträge beim Zahle abgebucht werden sollten auch beide auf der Rechnung stehen. Das sollte man dann mit einem eigenen PR machen.
> 
> Ja das stimmt. Hier würde ich es dann auch so machen, dass der Zahler verwendet wird, bei einem abweichenden Kontoinhaber aber nur seine Daten in der Rechnung verwendet werden und es trotzdem dem Mitglied zugeordnet bleibt.
> Dabei ist mir aufgefallen, dass die Mailadresse es abweichenden Kontoinhabers nur bei denLastschriften eingetragen wird und somit auch nur beim Versand von Prenotifications verwendet wird. Eigentlich müsste die ja auch bei den Spendenbescheinigungen und den Rechnungen verwendet werden.
> Insgesamt bin ich mir beim abweichendem Kontoinhaber unsicher und ich denke es gibt mehrere mögliche Anwendungsfälle:
> -Alles wird an das Mitglied geschickt, nur das Konto gehört jemandem anderen, hier wäre evtl. eine Rechnungskopie an den Kontoinhaber sinnvoll, am besten auf der Originalrechnung ein Vermerk wer bezahlt.
> -vor allem bei Kindern ist das Kind Mitglied aber Kontoinhaber und Rechnungsempfänger sind die Eltern
> 
>

2024-12-03 10:15 UTC, JohannMaierhofer commented
Bezüglich editieren des Zahler, Spendenbescheinigungen ohne Mitglied Referenz und der Mail Adresse des abweichenden Kontoinhaber habe ich mir auch Gedanken gemacht und dann letztendlich bei meinem Vorschlag gelandet. Alles hängt damit zusammen, dass man den abweichenden Kontoinhaber oder auch den Vollzahler wechseln kann bevor man die Spendenbescheinigung erzeugt.

Nehmen wir an wir haben ein Mitglied mit Vollzahler. Aus irgendeinem Grund muss er selbst etwas außerordentlich zahlen per Überweisung.
Man kann jetzt einen Zusatzbetrag einrichten und einen Abrechnungslauf machen. Jetzt steht aber der Vollzahler als Zahler in der Sollbuchung. Das muß ich editieren können und das Mitglied als Zahler eintragen. Also muß der Zahler editierbar sein. 
Der einfachere Weg hier wäre allerdings ohne Abrechnungslauf direkt die Sollbuchung zu erzeugen. Dies spricht wieder für die Möglichkeit Sollbuchungen auch manuell erzeugen zu können. 

Anderes Beispiel Vollzahler, es kann ja sein, dass jemand aus irgendeinem Grund keine Spendenbescheinigungen braucht und jetzt ausgetreten ist. Jetzt braucht plötzlich doch noch eine Spendenbescheinigung für die letzte Zahlung. Er ist nicht mehr in der Sollbuchung eingetragen. Ich kann aber jetzt trotzdem eine Spendenbescheinigung ohne Verweis auf das Mitglied erstellen und seinen Namen in die Bescheinigung eintragen. Das spricht dafür auch Spendenbescheinigungen ohne Referenz auf ein Mitglied zu erlauben und in diesem Fall auch erzeugen zu können. Damit wäre es aber auch nicht inkonsistent bei Löschen des Zahler die Spendenbescheinigungen bestehen zu lassen,da man sie auch ohne Zahler Mitglied erzeugen kann. 

Zu dem Mail Problem. Man hat den alternativen Kontoinhaber gewechselt und vorher vergessen die Spendenbescheinigung zu erstellen oder wie oben genannt den Fall, dass man ursprünglich keine gebraucht hat aber plötzlich doch. Erstellt man sie jetzt ist der eingetragene Zahler falsch. Wenn ich jetzt per Mail verschicke bekommt auch noch der falsche die Bescheinigung. Da dachte ich mir wenn man die Mail Adresse nicht nimmt muss man diese ausdrucken und da fällt es einem auf jeden Fall auf, das da der falsche Empfänger drauf steht. 
Man kann natürlich die Mailadresse in die Spendenbescheinigung als neues Attribut einbauen und dort editierbar machen. Dann kann man den anderen Zahler und Mail Adresse ändern, aber die Gefahr des versehentlich an den falschen schicken bleibt. 
Ich denke, das würde nur sauber gelöst werden wenn wir entweder keinen alternativen Kontoinhaber erlauben oder seine ganzen Daten in die Sollbuchung kopieren. Mit nicht erlauben meine ich nur noch den Weg mit Vollzahler unterstützen. Dann müsste man aber auch Nicht-Mitglieder als Vollzahler erlauben. Der alternative Kontoinhaber wäre dann eben als Nicht-Mitglied einzurichten. Der Fall, dass sich der alternative Kontoinhaber dauernd ändert, denke ich ist ja wohl eher selten. 

Für den Fall, dass der Zahler beim Erstellen der Spendenbescheinigung schon ausgetreten und gelöscht wurde hätte man da natürlich auch keine Mail Adresse. Hier bräuchte man dann doch noch die Mail Adresse als Attribut in der Spendenbescheinigung. Die würde dann aber nur manuell eingetragen.
So könnte ich es natürlich auch jetzt machen. Also das Attribut einführen aber von nirgends kopieren und nur manuell eintragen lassen. Die Mail Adresse würde auch bei verschicken nur benutzt werden wenn keine Referenz auf ein Mitglied existiert. Also nur bei alternativen Kontoinhaber. Beim eintragen der Mail Adresse sieht man dann auch ob die Spendenbescheinigung wirklich auf den richtigen Namen ausgestellt ist. 

Man könnte aber auch deine Idee umsetzen und eine Mail an das Mitglied und den alternativen Kontoinhaber schicken. Dann muss ich in der Spendenbescheinigung doch auch bei alternativen Kontoinhaber das Mitglied in die Spendenbescheinigung eintragen. Beim versenden muss dann eine Mail an das Mitglied gehen und falls eine in der Spendenbescheinigung eingetragen ist auch an diese. 
Ja, das könnt Sinn machen. Die Frage ist nur ob das verwirrt wenn in der Spendenbescheinigung das Mitglied als Spender steht, es aber doch ein anderer ist. Da sollten dann zwei Werte stehen. Also Mitglied und Spender. Ist Mitglied der Spender sind beide gleich. Bei Vollzahler ist der Spender der Vollzahler und bei alternativem Kontoinhaber ist der Spender leer. So wäre es konsistent. 


Wechselt man den

2024-12-03 14:00 UTC, lenilsas commented
> Ja, es sind zwei Felder. Ich hätte schreiben sollen "der Zahler zusätzlich angezeigt"
> Bei gleichzeitig suchen wusste ich nicht wie ich das machen sollte. Ich mache ein join von der Mitgliedskonto Tabelle mit dem Mitglied. Da nutze ich entweder mitgliedskonto.mitglied ist mitglied.id oder eben mitgliedkonto.zahler. Kann man da beim join mit OR beide Bedingungen angeben? Ich probierst mal.

ja, das sollte gehen

> Nachdem man aber Sollbuchungen auch manuell erstellen kann muss mann editieren können. Da sollten wir weiter nachdenken. Evtl. Ein Flag in der Sollbuchung ob manuell oder automatisch erzeugt.

Ja, das sehe ich auch so dass Sollbuchungen bearbeitbar sein sollen. Aber ich denke eine Checkobx unter Einstellungen "Sollbuchungen bearbeiten zulassen" würde helfen damit unerfahrene Nutzer den richtigen Workflow nutzen ohne inkosistenzen zu erzeugen.

> Doch, man kann Sachspendenbescheinigungen in der Liste mit dem Button unten ohne Mitglied erzeugen. Aber ja, bei Geldspenden haben wir das nicht. Eigentlich ist das inkonsistent. Sachspenden sollten auch durch eine Buchung hinterlegt sein.
> Mit Spendenbescheinigung ohne Mitglied sehe ich kein Problem. Der Name steht ja immer noch drinnen. Das ist wie bei Buchung, die bleiben ja auch erhalten. Und wegen der Aufbewahrungsfristen macht es ja Sinn diese zu behalten.

So meinte ich das nicht. ich denke man sollte konsequenter weise das erstellen von Geldspendenbescheinigungen ohne Mitglied und Sollbuchung ermöglichen, da sie eigentlich nicht für die Spendenbescheinigung nötig sind.

2024-12-03 14:02 UTC, lenilsas commented
Zur Mailadresse des Kontoinhabers:
Ich denke wir können es auch so lassen, es muss nur gut dokumentiert sein in welchem Fall welche Adresse und Mailadresse verwendet wird.

2024-12-03 14:08 UTC, JohannMaierhofer commented
> So meinte ich das nicht. ich denke man sollte konsequenter weise das erstellen von Geldspendenbescheinigungen ohne Mitglied und Sollbuchung ermöglichen, da sie eigentlich nicht für die Spendenbescheinigung nötig sind.

Das wäre einfach, man bräuchte einfach im Kontextmenü der Buchung die Option Spendenbescheinigung und erzeugt dann eine ohne Mitglied Referenz. Dann muss man einfach manuell die Spender Daten eintragen, im Prinzip so wie bei der Sachspende wenn es über den Button passiert. Das könnte ich mit extra PR machen.
Da kommt dann sicher wieder das mit der Mail Adresse in der Spendenbescheinigung auf. Das könnte man dann in diesem PR nochmal besprechen.

2024-12-03 14:17 UTC, lenilsas commented
> > So meinte ich das nicht. ich denke man sollte konsequenter weise das erstellen von Geldspendenbescheinigungen ohne Mitglied und Sollbuchung ermöglichen, da sie eigentlich nicht für die Spendenbescheinigung nötig sind.
> 
> Das wäre einfach, man bräuchte einfach im Kontextmenü der Buchung die Option Spendenbescheinigung und erzeugt dann eine ohne Mitglied Referenz. Dann muss man einfach manuell die Spender Daten eintragen, im Prinzip so wie bei der Sachspende wenn es über den Button passiert. Das könnte ich mit extra PR machen. Da kommt dann sicher wieder das mit der Mail Adresse in der Spendenbescheinigung auf. Das könnte man dann in diesem PR nochmal besprechen.

Das klingt sehr gut. Mit der Mailadresse können wir dann da noch mal schauen...

2024-12-03 14:29 UTC, JohannMaierhofer commented
> > Ja, es sind zwei Felder. Ich hätte schreiben sollen "der Zahler zusätzlich angezeigt"
> > Bei gleichzeitig suchen wusste ich nicht wie ich das machen sollte. Ich mache ein join von der Mitgliedskonto Tabelle mit dem Mitglied. Da nutze ich entweder mitgliedskonto.mitglied ist mitglied.id oder eben mitgliedkonto.zahler. Kann man da beim join mit OR beide Bedingungen angeben? Ich probierst mal.
> 
> ja, das sollte gehen

So einfach gehts doch nicht, dann hätte ich ja nur eine Spalte mitglied.name. Ich habe jetzt gelesen, dass man die gleiche Tabelle zweimal joinen kann. So müsste es gehen. Einmal join mit mitglied und dann nochmal mit Zahler und die Spalten unterscheidlich benennen. Dann kann ich ein Match auf die beiden Spalten machen.
Mal schauen ob das mit dem DBIterator geht, sonst muss man das über SQL machen.

2024-12-03 15:09 UTC, JohannMaierhofer commented
> So einfach gehts doch nicht, dann hätte ich ja nur eine Spalte mitglied.name. Ich habe jetzt gelesen, dass man die gleiche Tabelle zweimal joinen kann. So müsste es gehen. Einmal join mit mitglied und dann nochmal mit Zahler und die Spalten unterscheidlich benennen. Dann kann ich ein Match auf die beiden Spalten machen. Mal schauen ob das mit dem DBIterator geht, sonst muss man das über SQL machen.

Es hat geklappt, da habe ich wieder was gelernt.
        sollbuchungen.join("mitglied dasMitglied");
        sollbuchungen.addFilter("dasMitglied.id = mitgliedskonto.mitglied");
        sollbuchungen.join("mitglied derZahler");
        sollbuchungen.addFilter("derZahler.id = mitgliedskonto.zahler");

2024-12-03 20:22 UTC, JohannMaierhofer commented
Bezüglich des Editieren von Sollbuchungen bin ich inzwischen auch der Meinung, dass man das nicht zulassen sollte. Genauso wie die Spendenbescheinigungen.

Ich hatte ursprünglich dieses Szenario im Sinn.
Wir machen eine Abrechnung wobei ein Vollzahler eingetragen ist. Nach der Lastschrift merkt der Zahler dass er eigentlich nicht mehr zahlen wollte und nur vergessen hatte das zu melden. Evtl. wird die Lastschrift storniert und nun muss doch ein anderer bezahlen.
Da wir das Mitgliedskonto ausgleichen müssen, muss die neue Buchung der Sollbuchung zugewiesen werden. Jetzt wird aber dann die Spendenbescheinigung auf den falschen Zahler ausgestellt wenn ich den nicht in der Sollbuchung ändern kann.

Wenn wir aber das Feature machen, dass man die Spendenbescheinigung direkt an der Buchung erzeugen kann, dann könnte man sie erst erzeugen und dann der Sollbuchung zuweisen. Es stimmt dann zwar nicht der Zahler in der Sollbuchung mit dem in der Spendenbescheinigung überein, aber da man das nur manuell machen kann sollte das ok sein. Es ist ja nur wichtig, dass der Spender in der Spendenbescheinigung mit dem Zahler der Buchung überein stimmt. 

Ich würde das dann so machen, dass man zwar neue Sollbuchungen und Spendenbescheinigungen manuell anlegen kann aber später nicht mehr editieren kann. Beim manuellen anlegen der Spendenbescheinigung könnte man dann auch das Spender Feld freigeben, so dass man auch ein Mitglied oder Nicht-Mitglied auswählen kann. So kann man den Spender ohne Umweg über die Sollbuchung erstellen. Bei freien Spenden wird man sie auch nicht brauchen, es sei denn man will sie im Mitgliedskonto haben z.B. für den Kontoauszug.

Damit hätte man den bekannten automatisierten Weg, kann aber auch vereinfacht vorgehen. Ich glaube, das ist eine Runde Sache.

2024-12-04 12:10 UTC, JohannMaierhofer commented
Ich habe jetzt alles gemacht:
- Bei Sollbuchungen gleichzeitig nach Mitglied und Zahler filtern
- Bei Mitglied löschen die Meldung angepasst, also Spendenbescheinigung rausgenommen
- Sollbuchungen kann man jetzt nicht mehr editieren. Die automatischen sollte man sowieso nicht ändern und die manuellen muss man bei einer Fehleingabe dann halt löschen und neu eingeben. Neu anlegen geht noch. Das sollte Fehlbedienung vermeiden
- Auch die Spendenbescheinigungen kann man nicht mehr ändern. Ist das in dem oben beschriebenen Fall nötig, dann wird es das andere Feature geben, dass man auch Geldspendenbescheinigungen manuell erzeugen kann. Das werde ich aber erst machen wenn dieser PR übernommen ist. Da muss ich ja an die gleichen Dateien ran

2024-12-22 08:45 UTC, JohannMaierhofer commented
Ich das Blockieren der Editierbarkeit von Sollbuchungen wieder rückgängig gemacht. Das könnte man nach #547 evtl. nochmals besprechen.

2025-01-06 08:19 UTC, JohannMaierhofer commented
Ich habe das Bug Flag gesetzt weil es hat ein Fehler ist die Spendenbescheinigung auf die falsche Person auszustellen.
Derjenige der bezahlt, hat gespendet und muss darum auch die Spendenbescheinigung erhalten.

2025-01-18 19:00 UTC, tolot27 requested changes
Ich muss es noch live testen.

2025-01-19 17:23 UTC, JohannMaierhofer commented on src/de/jost_net/JVerein/server/MitgliedskontoImpl.java
> +    return (Mitglied) cache.get(o);
Ich bin ja auch dafür redundanten Code zu vermeiden. Ich habe auch damals den FilterControl und DruckMailControl eingeführt weil jeder Control der sie jetzt benutzt für die gleichen Filter Attribute die gleichen Methoden implementiert hatte. Das hat sehr viel redundanten Code entfernt. 
Ich verstehe allerdings den Vorschlag mit Interfaces nicht ganz. Ein Interface definiert doch nur die Methoden Signatur. Jeder der es implementiert muss es doch auscodieren. Wie spare ich da redundanten Code.
Wie geht das mit defaults?

2025-01-19 18:32 UTC, tolot27 commented on src/de/jost_net/JVerein/server/MitgliedskontoImpl.java
> +    return (Mitglied) cache.get(o);
Siehe https://www.baeldung.com/java-static-default-methods bzw. https://docs.oracle.com/javase/tutorial/java/IandI/defaultmethods.html

2025-01-19 19:01 UTC, JohannMaierhofer commented on src/de/jost_net/JVerein/server/MitgliedskontoImpl.java
> +    return (Mitglied) cache.get(o);
Danke, ich muss doch langsam anfangen Java zu lernen.

2025-01-21 10:18 UTC, JohannMaierhofer commented on src/de/jost_net/JVerein/server/MitgliedImpl.java
> +  }
gemacht

2025-01-21 10:19 UTC, JohannMaierhofer commented on src/de/jost_net/JVerein/server/MitgliedskontoImpl.java
> +    return (Mitglied) cache.get(o);
Ich würde das dann separat angehen. Die gleich Verdoppelung gibt es ja bei den DB Klassen öfters.

2025-01-21 10:20 UTC, JohannMaierhofer commented
Migration ist bei 459. Der PR muss also nach der Mittelverwendung übergeben werden.

2025-01-24 22:16 UTC, lenilsas approved these changes

2025-01-25 12:47 UTC, tolot27 commented
Ich kann leider keine automatischen Spendenbescheinigungen erzeugen. Wenn ich es über das Kontextmenü bei einem Mitglied mache, kommt die Fehlermeldung, dass keine relevanten Buchungen gefunden wurden. Sie sind jedoch da. Also alles nochmal geprüft. Das/die (Nicht-)Mitglieder haben jeweils eine vollständige Adresse. Alle Spendeneingänge, für die ich eine Spendenquittung benötige, sind auf "40450 Geldzuwendungen gegen Zuwendungsbestätigung" gebucht (ideeller Bereich) und bei dieser Buchungsart ist auch "Spende" aktiv. Außerdem ist bei den Spendeneingängen eine Sollbuchung zugeordnet, was ich auch im Mitgliedskonto geprüft habe. Dort kann ich auf der Istbuchung über Rechtsklick eine Spendenbescheinigung erstellen. Da übernimmt er jedoch keine Adressdaten. Das könnte der PR noch implementieren, da Informationen ja vorliegen.

Warum ich sonst keine Spendenbescheinigungen erstellen kann, kann ich mir nicht wirklich erklären. Könnte es an den Sollbuchungspositionen liegen? Was kann ich sonst noch prüfen?

Komisch finde ich, dass ich schon mal eine Sachspende erzeugt habe, die nun weg ist.

2025-01-25 12:54 UTC, JohannMaierhofer commented
> Ich kann leider keine automatischen Spendenbescheinigungen erzeugen. Wenn ich es über das Kontextmenü bei einem Mitglied mache, kommt die Fehlermeldung, dass keine relevanten Buchungen gefunden wurden. Sie sind jedoch da. Also alles nochmal geprüft. Das/die (Nicht-)Mitglieder haben jeweils eine vollständige Adresse. Alle Spendeneingänge, für die ich eine Spendenquittung benötige, sind auf "40450 Geldzuwendungen gegen Zuwendungsbestätigung" gebucht (ideeller Bereich) und bei dieser Buchungsart ist auch "Spende" aktiv. Außerdem ist bei den Spendeneingängen eine Sollbuchung zugeordnet, was ich auch im Mitgliedskonto geprüft habe. Dort kann ich auf der Istbuchung über Rechtsklick eine Spendenbescheinigung erstellen. Da übernimmt er jedoch keine Adressdaten. Das könnte der PR noch implementieren, da die Adressinformationen ja vorliegen.
> 
> Warum ich sonst keine Spendenbescheinigungen erstellen kann, kann ich mir nicht wirklich erklären. Könnte es an den Sollbuchungspositionen liegen? Was kann ich sonst noch prüfen?
> 
> Komisch finde ich, dass ich schon mal eine Sachspende erzeugt habe, die nun weg ist.

    Ist auch das gegeben: 
Der Betrag der Bescheinigung muss gleich oder größer sein als der Mindestbetrag der unter Administration->Einstellungen->Spendenbescheinigungen eingetragen ist.
Und es existiert noch keine Spendenbescheinigung für die Buchung.

2025-01-25 13:19 UTC, JohannMaierhofer commented
Ich habe es gerade nochmal probiert. Bei mir geht alles. Auch wird bei manueller Spendenbescheinigung die Adresse des Mitglieds übernommen.

Du musst aber noch auf folgendes aufpassen. Wenn du einen anderen Zahler gewählt hast. Dann wird die Spendenbescheinigung beim Zahler ausgestellt und nicht beim Mitglied mit der Sollbuchung.

Wenn du beim Mitglied den Menüpunkt wählst dann wird keine passende Buchung gefunden weil das Mitglied nichts gespendet hat. Wenn du das aber beim Zahler machst wird die Buchung gefunden.
Wählst du direkt die Istbuchung beim Mitglied aus, wird die Spendenbescheinigung erstellt, es werden aber die Adressdaten des Zahlers eingetragen, weil ja auf diesen die Bescheinigung ausgestellt wird. Wenn der in deinem Fall keine Adresse hat dann fehlen die Daten in der Bescheinigung.

Ich vermute mal, das ist dein Problem.

2025-01-25 14:40 UTC, tolot27 commented
> ```
> Ist auch das gegeben: 
> ```
> 
> Der Betrag der Bescheinigung muss gleich oder größer sein als der Mindestbetrag der unter Administration->Einstellungen->Spendenbescheinigungen eingetragen ist. Und es existiert noch keine Spendenbescheinigung für die Buchung.

Ja natürlich. Ich habe Spenden von 300 bis 3000 € und zwar mehrere.

> Wenn du beim Mitglied den Menüpunkt wählst dann wird keine passende Buchung gefunden weil das Mitglied nichts gespendet hat. Wenn du das aber beim Zahler machst wird die Buchung gefunden. Wählst du direkt die Istbuchung beim Mitglied aus, wird die Spendenbescheinigung erstellt, es werden aber die Adressdaten des Zahlers eingetragen, weil ja auf diesen die Bescheinigung ausgestellt wird. Wenn der in deinem Fall keine Adresse hat dann fehlen die Daten in der Bescheinigung.
> 
> Ich vermute mal, das ist dein Problem.

Nein, ist es nicht. Da ich bei diesem Beispielmitglied ja zum Mitgliedskonto gewechselt bin und da die Spendenbuchung sehe.

Außerdem habe ich auch Nicht-Mitglieder angelegt (z. B. für Fördervereine, wo man übrigens Vor- und Nachnamen eintragen muss, was es bei denen nicht gibt). Auch hier funktioniert es nicht.
Eine Sachspendenbescheinigung kann ich erzeugen. Da wird auch die Adresse eingetragen, allerdings nicht in Zeile 1. Die bleibt leer. Ich nehme an, weil ich keine Anrede hinterlegt habe.

2025-01-25 14:46 UTC, JohannMaierhofer commented
> Nein, ist es nicht. Da ich bei diesem Beispielmitglied ja zum Mitgliedskonto gewechselt bin und da die Spendenbuchung sehe.

Heißt das, dass in deinem Beispiel der Zahler in der Sollbuchung das Mitglied selbst ist? Wenn das so ist verstehe ich es auch nicht. Dann schaue ich es mir nochmals an.

2025-01-25 14:48 UTC, lenilsas commented
Hat das denn mit diesem PR zu tun oder war es vorher schon so?

2025-01-25 15:05 UTC, tolot27 commented
> > Nein, ist es nicht. Da ich bei diesem Beispielmitglied ja zum Mitgliedskonto gewechselt bin und da die Spendenbuchung sehe.
> 
> Heißt das, dass in deinem Beispiel der Zahler in der Sollbuchung das Mitglied selbst ist? Wenn das so ist verstehe ich es auch nicht. Dann schaue ich es mir nochmals an.

Ich habe mir mal das Mitgliedskonto eines Nicht-Mitglieds für die Spende angeschaut:

![image](https://github.com/user-attachments/assets/6e30f1c8-f089-46cd-acb7-164d4066d665)

Hier fehlt ja fast alles drin. Wenn ich mir die Istbuchung dazu anschaue, ist Buchungsklasse und Buchungsart gesetzt.

> Hat das denn mit diesem PR zu tun oder war es vorher schon so?

Vorher hab ich es noch nicht benutzt, da ich auf diesen PR gewartet habe und 2024 unser erstes volles Geschäftsjahr ist.

2025-01-25 15:10 UTC, JohannMaierhofer commented
Also ich verstehe das Problem nicht. Anscheinend kann er keine automatischen Spendenbescheinigungen mehr erstellen. Das ging natürlich in der Vergangenheit und sollte weiter gehen. Bei mir geht es auch.

Darum wollte ich jetzt verstehen was hier anders ist.

Also wenn man in das Mitgliedskonto des Mitglieds geht und dort ist eine Sollbuchung und in der Sollbuchung steht als Zahler ein anderes Mitglied, z.B. der Vollzahler. Wenn man dann das Mitglied auswählt und automatisch Spendenbescheinigungen erzeugt dann wird diese Sollbuchung jetzt nicht berücksichtigt weil es ja keine für das Mitglied ist. Wenn man das im Vollzahler macht dann wird die Spendenbescheinigung erzeugt, auch wenn dort die Sollbuchung nicht existiert. Nur wenn man die Spendenbescheinigung manuell erzeugt und die Istbuchung auswählt wird sie erzeugt, aber mit den Daten des Zahlers.
Die Auswahl beim Mitglied ist so wie aus dem Sollbuchung View wenn man die automatische Generierung wählt. Dann werden alle Buchungen für die Mitlieder gesucht, beim Zahler eben auch welche die bei anderen Mitgliedern hängen. All die gefundenen Buchungen gehen in die gleiche Spendenbescheinigung.

Wenn der Testfall aber so ist, dass es keine Vollzahler gibt und in der Sollbuchung das Mitglied selbst als Zahler steht dann sollte natürlich alles so gehen wie bisher. Bei mir geht das. Bei tolot anscheinend nicht.

2025-01-25 15:19 UTC, lenilsas commented
> Hier fehlt ja fast alles drin. Wenn ich mir die Istbuchung dazu anschaue, ist Buchungsklasse und Buchungsart gesetzt.

Was fehlt dir denn? Wahrscheinlich hast du die Sollbuchung ohne Abrechnungslauf erstellt, daher ist der auch nicht gesetzt. Durch #547 verwenden wir Buchungsart, Buchungsklasse, Nettobetrag, Steuerbetrag und Steuersatz aus der Sollbuchung nicht mehr, das steht jetzt in der Sollbuchungsposition. Nur zur Abwärtskompatibilität haben wir die Spalten gelassen. Du hast das ja selber Approved, daher sollte dir das eigentlich klar sein. Eine Rechnung hast du wahrscheinlich nicht darüber erstellt und der Zahler wurde ja erst mit diesem PR eingeführt.

2025-01-25 15:27 UTC, tolot27 commented
Die zugrundeliegende Abfrage ist:

```SQL
SELECT buchung.id
	FROM buchung JOIN buchungsart ON buchung.buchungsart = buchungsart.id
		JOIN mitgliedskonto ON buchung.mitgliedskonto = mitgliedskonto.id
    WHERE buchungsart.spende = true
        AND mitgliedskonto.zahler = ?
        AND buchung.spendenbescheinigung IS NULL
        AND buchung.mitgliedskonto IS NOT NULL
	ORDER BY buchung.datum;
```

Das `mitgliedskonto.zahler = ?` ist das Problem. Das wird erst mit diesem PR gesetzt. Somit geht es bei allen früheren Buchungen nicht. Und ja, ich mache keinen Abrechnungslauf und erzeuge keine Sollbuchung. Wozu sollte ich das bei einem Spendeneingang auch tun? Nun muss ich die Sollbuchung erzeugen, was mir einleuchtet, da ja das Mitglied (bzw. eigentlich nur irgend ein Kontakt) irgendwie zugeordnet werden muss, um an die Adressdaten zu kommen. Das mache ich bei dem Zahlungseingang Rechtsklick mache, "Sollbuchung zuordnen" wähle und dann "Sollbuchung erzeugen und Istbuchung zuordnen".

2025-01-25 15:28 UTC, JohannMaierhofer commented
Das Problem hier ist, dass der Zahler nicht gesetzt ist.
In der Migration zu diesem Feature wird bei allen bestehenden Sollbuchungen das Mitglied in den Zahler kopiert. Wenn die also schon vor diesem Feture existiert haben sollte der Zahler gesetzt sein.

Ich glaube das Problem kommt daher, dass das Projekt schon früher mit diesem Feature getestet wurde und die Migration gelaufen ist. Später wurde dann mit einer Version ohne diesem Feature die Sollbuchungen erzeugt. Da wurde dann natürlich kein Zahler gesetzt weil das Feature nicht in der SW war. Wenn man jetzt wieder Sollbuchungen erzeugt wird der Zahler gesetzt.

2025-01-25 15:38 UTC, tolot27 commented
> Du hast das ja selber Approved, daher sollte dir das eigentlich klar sein.
Bitte sehe mir nach, dass ich nicht alle Änderungen und insbesondere die left-overs im Kopf habe. 😏

> Eine Rechnung hast du wahrscheinlich nicht darüber erstellt.
Wieso sollte ich über eine Spende eine Rechnung erstellen? Das halte ich für intrinsisch unlogisch.

2025-01-25 15:38 UTC, JohannMaierhofer commented
> Nun habe ich `update mitgliedskonto set zahler = mitglied` manuell auf der DB ausgeführt und alles funktioniert.

Da bin ich aber jetzt erleichtert, ich dachte schon ich habe Mist gebaut.

2025-01-25 15:44 UTC, JohannMaierhofer commented
> Nun muss ich die Sollbuchung erzeugen, was mir einleuchtet, da ja das Mitglied (bzw. eigentlich nur irgend ein Kontakt) irgendwie zugeordnet werden muss, um an die Adressdaten zu kommen.

Ich hatte hier schon mal angedeutet, dass ich überlege eine Spendenbescheinigung auch ohne Sollbuchung erstellen zu können, also manuell über das Buchung Menü. In der Spendenbescheinigung ist ja jetzt auch das Mitglied zu sehen. Wenn ich das editierbar mache kann man bei auswählen die Adressdaten holen und setzen.

Das ganze geht aber dann halt nur manuell. Der automatische Suchlauf braucht die Sollbuchung wegen der Zuordnung zu Mitglied.

Ich wollte das aber erst nach diesem Feature hier machen und habe darum so lange gewartet. Aber demnächst vielleicht.

2025-01-25 15:56 UTC, tolot27 requested changes
> Dort kann ich auf der Istbuchung über Rechtsklick eine Spendenbescheinigung erstellen. Da übernimmt er jedoch keine Adressdaten. Das könnte der PR noch implementieren, da die Adressinformationen ja vorliegen.

Das geht nun auch, da durch das Update-Statement der zahler nachgetragen wurde.

2025-01-25 15:56 UTC, tolot27 commented on src/de/jost_net/JVerein/util/SpbAdressaufbereitung.java
> +      adresse.add(m.getAnrede());
Kannst du hier auch noch einen Check auf "null/empty" einbauen? Ich pflege die Anrede eigentlich nie und so bleibt die Zeile 1 immer frei.

2025-01-25 15:56 UTC, tolot27 commented on src/de/jost_net/JVerein/util/SpbAdressaufbereitung.java
> +      adresse.add(m.getKtoiAnrede());
Hier dann auch der null/empty check.

2025-01-25 15:56 UTC, tolot27 commented on src/de/jost_net/JVerein/util/SpbAdressaufbereitung.java
> +      adresse.add(m.getStaat());
Hier und unten könnte man noch prüfen ob der Staat der Adresse gleich dem Staat des Sitzes des Vereins ist und ihn dann auch unterdrücken. Momentan sieht das bisl komisch aus, dass er auf manchen Spendenbescheinigungen auftaucht und dann auch noch in Großbuchstaben.

2025-01-25 15:57 UTC, tolot27 commented on src/de/jost_net/JVerein/util/SpbAdressaufbereitung.java
> +      adresse.add(m.getAnrede());
Das könnten wir auch in einem weiteren PR machen, da momentan nur noch mein Approval fehlt. Sonst müssten wieder alle approven.

2025-01-25 16:03 UTC, JohannMaierhofer commented on src/de/jost_net/JVerein/util/SpbAdressaufbereitung.java
> +      adresse.add(m.getStaat());
Eigentlich ist es so wie früher, dass man beim Mitglied einfach keinen Staat setzt wenn das Mitglied im Inland ist. Wenn er nicht gesetzt ist, sollte hier auch kein Staat stehen. Wenn man ihn setzt taucht er auch auf.
Also hat es der User selbst in der Hand was er will.
Das ist ja auch beim Adressblatt so. Da wollte ich auch bei Deutschen Adressen keinen Staat. Darum haben wir das Staat Feature ja auch so gemacht, dass man wie früher keinen setzen muss.

2025-01-25 16:10 UTC, JohannMaierhofer commented on src/de/jost_net/JVerein/util/SpbAdressaufbereitung.java
> +      adresse.add(m.getAnrede());
Darüber hatte ich auch nachgedacht. Wenn man aber auch einige mit Anrede hat, dann schaut der SpendenbescheinigungListeView etwas seltsam aus, weil dann bei manchen der Name in Spalte Zeile 1 steht und bei anderen in Zeile 2. Und der ganze Rest ist natürlich auch um eine Spalte verschoben.
Man muss auch evtl. die Liste der Spendenbescheinigungen an das Finanzamt geben. Dazu habe ich ja eingebaut, dass man diese Liste auch ausdrucken kann.
Es schaut halt etwas seltsam aus wenn die Namen da nicht in der gleichen Spalte sind. Da finde ich es dann besser wenn die Einträge in Spalte 1 dann einfach leer sind.

Oder gibt es da eine Anforderung, dass die erste Zeile nicht leer sein darf?

2025-01-25 16:16 UTC, tolot27 commented on src/de/jost_net/JVerein/util/SpbAdressaufbereitung.java
> +      adresse.add(m.getAnrede());
> Oder gibt es da eine Anforderung, dass die erste Zeile nicht leer sein darf?

Nicht dass ich wüsste. Das Formular wird ja vom FA nicht elektronisch eingelesen. Okay, dann lassen wir es so.

2025-01-25 16:18 UTC, tolot27 commented on src/de/jost_net/JVerein/util/SpbAdressaufbereitung.java
> +      adresse.add(m.getStaat());
Hm, ich meinte, aus irgendeinem Grund musste Staat mal ausgefüllt werden. Dann lösche ich ihn bei mir einfach aus der DB, zumindest DEUTSCHLAND.

2025-01-25 16:18 UTC, tolot27 approved these changes
Richtig hilfreiches Feature! Danke!😄

2025-01-25 16:19 UTC, merged

2025-01-25 17:08 UTC, tolot27 commented
Vielleicht können wir die merge commit comments in Zukunft etwas aufräumen und als Basis für eine Zusammenfassung der wichtigsten Änderungen verwenden (siehe https://github.com/openjverein/jverein/pull/606#issuecomment-2614019193). Der merge commit comment dieses PRs (96fe123) sieht jedenfalls ziemlich uggly aus. 🙈