New font PTSans for forms
openjverein/jverein pull request #60
Opened 2023-10-30 09:02 UTC by dippeal

2023-10-30 15:43 UTC, MSchmalzl approved these changes

2023-10-30 20:15 UTC, NicoB77 requested changes
Das Encoding wurde in UTF8 geändert, Source-Encoding ist aber ISO-8859-1

2023-10-30 20:33 UTC, dippeal commented
> Das Encoding wurde in UTF8 geändert, Source-Encoding ist aber ISO-8859-1

Angepasst in [a876927](https://github.com/openjverein/jverein/pull/60/commits/a876927b885a3e8e40f9ba029d66476f5e8cc2b8)

2023-11-01 07:51 UTC, MSchmalzl commented
Ist das Encoding eine globale Eigenschaft? Bzw. was spricht gegen UTF-8?

2023-11-01 09:07 UTC, NicoB77 commented
Das Encoding ist global. Es wäre auch gar nicht wünschenswert, es pro Datei vorzugeben. Und weil global ISO-8859-1 eingestellt ist, werden für in UTF-8 kodierte Java-Dateien Sonderzeichen in der GUI falsch dargestellt. Natürlich könnte man das Encoding global in UTF-8 ändern, aber das wäre definitiv ein eigener Pull-Request.

2023-11-01 09:11 UTC, NicoB77 approved these changes

2023-11-01 09:29 UTC, MSchmalzl approved these changes

2023-11-01 09:30 UTC, merged