Einige Bugfixes
openjverein/jverein pull request #7
Opened 2022-06-12 13:32 UTC by NicoB77

Fixes für #4, #5 und #6.

2022-06-13 09:30 UTC, phschoen requested changes
only default ports are missing but i could be wrong, that they will be added by java.
After explanation i would merge it.

2022-06-13 09:30 UTC, phschoen commented on src/de/jost_net/JVerein/server/EinstellungImpl.java
> -    if (ret == null)
why remove the default port?

2022-06-13 09:30 UTC, phschoen commented on src/de/jost_net/JVerein/gui/control/EinstellungControl.java
> +        e.setSmtpPort(null);
why not use in these error cases a default port?

2022-06-13 09:30 UTC, phschoen commented on src/de/jost_net/JVerein/gui/control/EinstellungControl.java
> +        e.setImapPort(null);
same here ? 

why not use in these error cases a default port?

2022-06-13 11:34 UTC, NicoB77 commented
JavaMail verwendet Standardwerte, wenn keine Ports vorgegeben sind. Es kam mir sinnvoller vor, sie dort setzen zu lassen, anstatt sie im JVerein-Code noch einmal zu hinterlegen.

2022-08-09 08:45 UTC, phschoen approved these changes

2022-08-09 08:47 UTC, merged